#!/usr/bin/python3

import sys

def factorize(number):
    factors = []
    for i in range(2, number):
        if number % i == 0:
            factors.append((i, number // i))
    return factors

def main(filename):
    try:
        with open(filename, 'r') as file:
            lines = file.readlines()
            for line in lines:
                number = int(line.strip())
                factorizations = factorize(number)
                for factorization in factorizations:
                    print(f'{number}={factorization[0]}*{factorization[1]}')
    except FileNotFoundError:
        print(f"File '{filename}' not found.")
    except ValueError:
        print("Invalid number in the file. All lines must contain natural numbers greater than 1.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
    else:
        main(sys.argv[1])
